"""Tests for the dynamical Lie algebra closure helpers.

Closure dimensions are validated against closed-form values: the single-qubit
algebra su(2) has dimension 3, and the matchgate algebra so(2n) generated by
{Z_k} u {X_k X_{k+1}} has dimension n(2n-1).
"""

from itertools import combinations

import numpy as np
import pytest

from qml_essentials.algebra import (
    lie_closure_paulis,
    lie_closure_matrices,
    matchgate_generators,
    matchgate_basis,
    dim_so2n,
    g_purity_from_basis,
    g_purity_matrix,
    symmetric_pauli_sum,
    sn_equivariant_generators,
    sn_equivariant_observable,
)
from qml_essentials.operations import PauliWord, state_expectation
from qml_essentials.states import haar_state

_X = np.array([[0, 1], [1, 0]], dtype=complex)
_Y = np.array([[0, -1j], [1j, 0]], dtype=complex)


def _matchgate_generators(n):
    """Matchgate DLA generators {Z_k} u {X_k X_{k+1}}."""
    gens = []
    for k in range(n):
        s = ["I"] * n
        s[k] = "Z"
        gens.append("".join(s))
    for k in range(n - 1):
        s = ["I"] * n
        s[k] = "X"
        s[k + 1] = "X"
        gens.append("".join(s))
    return gens


def _product_state(theta):
    """|psi> = prod_i RY(theta_i)|0>, qubit 0 leftmost."""
    psi = np.array([1.0], dtype=complex)
    for t in theta:
        psi = np.kron(psi, np.array([np.cos(t / 2), np.sin(t / 2)], dtype=complex))
    return psi


def _normalised_pauli_mats(strings, n):
    """HS-orthonormal Hermitian matrices P/sqrt(2^n) for the given Pauli strings."""
    norm = np.sqrt(2.0**n)
    return [
        np.asarray(PauliWord.from_pauli_string(s, list(range(n)), n).to_matrix()) / norm
        for s in strings
    ]


class TestLieClosurePaulis:
    @pytest.mark.unittest
    def test_su2_closure(self):
        basis = lie_closure_paulis(["X", "Y"])
        assert {pw.to_pauli_string() for pw in basis} == {"X", "Y", "Z"}

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_matchgate_dimension(self, n):
        basis = lie_closure_paulis(_matchgate_generators(n))
        assert len(basis) == n * (2 * n - 1)

    @pytest.mark.unittest
    def test_accepts_pauliword_inputs(self):
        gens = [PauliWord.from_pauli_string(s, [0], 1) for s in ("X", "Y")]
        basis = lie_closure_paulis(gens)
        assert {pw.to_pauli_string() for pw in basis} == {"X", "Y", "Z"}


class TestLieClosureMatrices:
    @pytest.mark.unittest
    def test_su2_closure_dimension(self):
        assert len(lie_closure_matrices([_X, _Y])) == 3

    @pytest.mark.unittest
    def test_orthonormal_hermitian(self):
        basis = lie_closure_matrices([_X, _Y])
        for B in basis:
            assert np.allclose(B, B.conj().T)
        gram = np.array(
            [[np.vdot(a.reshape(-1), b.reshape(-1)) for b in basis] for a in basis]
        )
        assert np.allclose(gram, np.eye(len(basis)))

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_matchgate_dimension_matches_paulis(self, n):
        gens = _matchgate_generators(n)
        mats = [
            np.asarray(PauliWord.from_pauli_string(s, list(range(n)), n).to_matrix())
            for s in gens
        ]
        basis = lie_closure_matrices(mats)
        assert len(basis) == n * (2 * n - 1)
        assert len(basis) == len(lie_closure_paulis(gens))


class TestMatchgateConstructors:
    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_dim_so2n(self, n):
        assert dim_so2n(n) == n * (2 * n - 1)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_basis_length(self, n):
        assert len(matchgate_basis(n)) == dim_so2n(n)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_generators_count(self, n):
        assert len(matchgate_generators(n)) == n + (n - 1)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_generators_match_reference(self, n):
        assert matchgate_generators(n) == _matchgate_generators(n)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_basis_equals_closure(self, n):
        # Explicit construction must equal the frontier-expansion closure.
        closure = {
            pw.to_pauli_string() for pw in lie_closure_paulis(matchgate_generators(n))
        }
        assert set(matchgate_basis(n)) == closure


class TestGPurity:
    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_from_basis_all_zero_value(self, n):
        # |0...0>: <Z_k> = 1 for the n on-site terms, all X/Y pair strings -> 0.
        psi = np.zeros(2**n, dtype=complex)
        psi[0] = 1.0
        assert np.isclose(
            g_purity_from_basis(psi, matchgate_basis(n)), float(n), atol=1e-10
        )

    @pytest.mark.unittest
    def test_from_basis_accepts_words_and_strings(self):
        n = 2
        psi = _product_state(np.array([0.7, 1.3]))
        words = lie_closure_paulis(matchgate_generators(n))
        strs = [pw.to_pauli_string() for pw in words]
        assert np.isclose(
            g_purity_from_basis(psi, words),
            g_purity_from_basis(psi, strs),
            atol=1e-12,
        )

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_matrix_matches_from_basis(self, n):
        # P_g^HS = P_g / 2^n on the same DLA (HS-orthonormal P_mu / sqrt(2^n)).
        theta = np.linspace(0.3, 1.1, n)
        psi = _product_state(theta)
        strings = matchgate_basis(n)
        p_str = g_purity_from_basis(psi, strings)
        p_mat = g_purity_matrix(psi, _normalised_pauli_mats(strings, n))
        assert np.isclose(p_mat, p_str / 2**n, atol=1e-10)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_matrix_basis_independent(self, n):
        # g_purity_matrix is invariant to the HS-orthonormal basis choice:
        # lie_closure_matrices output equals the manually normalised Pauli basis.
        theta = np.linspace(0.2, 1.4, n)
        psi = _product_state(theta)
        manual = _normalised_pauli_mats(matchgate_basis(n), n)
        closed = lie_closure_matrices(
            [
                np.asarray(
                    PauliWord.from_pauli_string(s, list(range(n)), n).to_matrix()
                )
                for s in matchgate_generators(n)
            ]
        )
        assert np.isclose(
            g_purity_matrix(psi, manual), g_purity_matrix(psi, closed), atol=1e-10
        )


def _pauli_matrix(s, n):
    return np.asarray(PauliWord.from_pauli_string(s, list(range(n)), n).to_matrix())


def _sum_pair(ch, n):
    """Reference Sigma_{j<k} P_j P_k built directly from PauliWord."""
    acc = np.zeros((2**n, 2**n), dtype=complex)
    for j, k in combinations(range(n), 2):
        s = ["I"] * n
        s[j] = ch
        s[k] = ch
        acc += _pauli_matrix("".join(s), n)
    return acc


def _swap_perm(n, a, b):
    """Permutation matrix swapping qubits a and b (qubit 0 leftmost)."""
    P = np.zeros((2**n, 2**n))
    for x in range(2**n):
        bits = [(x >> (n - 1 - q)) & 1 for q in range(n)]
        bits[a], bits[b] = bits[b], bits[a]
        y = sum(b_ << (n - 1 - q) for q, b_ in enumerate(bits))
        P[y, x] = 1.0
    return P


class TestSymmetricPauliSum:
    @pytest.mark.unittest
    def test_locality1_Z(self):
        # Z_0 + Z_1 = diag(2, 0, 0, -2).
        M = symmetric_pauli_sum("Z", 2, 1)
        assert np.allclose(np.diag(M).real, [2.0, 0.0, 0.0, -2.0])
        assert np.allclose(M, np.diag(np.diag(M)))

    @pytest.mark.unittest
    def test_locality2_equals_xx(self):
        # The only pair on 2 qubits is X_0 X_1.
        assert np.allclose(symmetric_pauli_sum("X", 2, 2), _pauli_matrix("XX", 2))

    @pytest.mark.unittest
    @pytest.mark.parametrize("pauli", ["X", "Y", "Z"])
    @pytest.mark.parametrize("n", [2, 3])
    @pytest.mark.parametrize("locality", [1, 2])
    def test_hermitian(self, pauli, n, locality):
        M = symmetric_pauli_sum(pauli, n, locality)
        assert M.shape == (2**n, 2**n)
        assert np.allclose(M, M.conj().T)

    @pytest.mark.unittest
    def test_validation(self):
        with pytest.raises(ValueError):
            symmetric_pauli_sum("A", 2, 1)
        with pytest.raises(ValueError):
            symmetric_pauli_sum("X", 2, 3)


class TestSnEquivariant:
    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_generators_count_and_shape(self, n):
        gens = sn_equivariant_generators(n)
        assert len(gens) == 3
        for G in gens:
            assert G.shape == (2**n, 2**n)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n,dim", [(2, 9), (3, 19), (4, 33), (5, 54)])
    def test_dla_dimension(self, n, dim):
        # Exact verified dimensions; the closure is polynomial (sub-full),
        # there is no clean global closed form (binom(n+3,3) breaks at n>=4).
        basis = lie_closure_matrices(sn_equivariant_generators(n))
        assert len(basis) == dim
        assert len(basis) < 4**n - 1

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_generators_equivariant_under_swap(self, n):
        P = _swap_perm(n, 0, 1)
        for G in sn_equivariant_generators(n):
            assert np.allclose(P @ G @ P.T, G)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_observable_value_and_equivariance(self, n):
        obs_mat = sn_equivariant_observable(n)
        assert np.allclose(obs_mat, obs_mat.conj().T)
        assert np.allclose(obs_mat, (2.0 / (n * (n - 1))) * _sum_pair("X", n))
        P = _swap_perm(n, 0, 1)
        assert np.allclose(P @ obs_mat @ P.T, obs_mat)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [3, 4])
    def test_observable_expectation_termwise(self, n):
        # Term-by-term expectation (no dense operator) matches <psi|O|psi>.
        psi = haar_state(n, seed=0)
        dense = np.vdot(psi, sn_equivariant_observable(n) @ psi).real
        c = 2.0 / (n * (n - 1))
        termwise = c * sum(
            state_expectation(
                "".join("X" if q in (j, k) else "I" for q in range(n)), psi
            ).real
            for j, k in combinations(range(n), 2)
        )
        assert np.isclose(dense, termwise, atol=1e-10)
