"""Tests for the dynamical Lie algebra closure helpers.

Closure dimensions are validated against closed-form values: the single-qubit
algebra su(2) has dimension 3, and the matchgate algebra so(2n) generated by
{Z_k} u {X_k X_{k+1}} has dimension n(2n-1).
"""

import numpy as np
import pytest

from qml_essentials.algebra import (
    lie_closure_paulis,
    lie_closure_matrices,
    matchgate_generators,
    matchgate_basis,
    dim_so2n,
    g_purity_from_basis,
    g_purity_matrix,
)
from qml_essentials.operations import PauliWord

_X = np.array([[0, 1], [1, 0]], dtype=complex)
_Y = np.array([[0, -1j], [1j, 0]], dtype=complex)


def _matchgate_generators(n):
    """Matchgate DLA generators {Z_k} u {X_k X_{k+1}}."""
    gens = []
    for k in range(n):
        s = ["I"] * n
        s[k] = "Z"
        gens.append("".join(s))
    for k in range(n - 1):
        s = ["I"] * n
        s[k] = "X"
        s[k + 1] = "X"
        gens.append("".join(s))
    return gens


def _product_state(theta):
    """|psi> = prod_i RY(theta_i)|0>, qubit 0 leftmost."""
    psi = np.array([1.0], dtype=complex)
    for t in theta:
        psi = np.kron(psi, np.array([np.cos(t / 2), np.sin(t / 2)], dtype=complex))
    return psi


def _normalised_pauli_mats(strings, n):
    """HS-orthonormal Hermitian matrices P/sqrt(2^n) for the given Pauli strings."""
    norm = np.sqrt(2.0**n)
    return [
        np.asarray(PauliWord.from_pauli_string(s, list(range(n)), n).to_matrix()) / norm
        for s in strings
    ]


class TestLieClosurePaulis:
    @pytest.mark.unittest
    def test_su2_closure(self):
        basis = lie_closure_paulis(["X", "Y"])
        assert {pw.to_pauli_string() for pw in basis} == {"X", "Y", "Z"}

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_matchgate_dimension(self, n):
        basis = lie_closure_paulis(_matchgate_generators(n))
        assert len(basis) == n * (2 * n - 1)

    @pytest.mark.unittest
    def test_accepts_pauliword_inputs(self):
        gens = [PauliWord.from_pauli_string(s, [0], 1) for s in ("X", "Y")]
        basis = lie_closure_paulis(gens)
        assert {pw.to_pauli_string() for pw in basis} == {"X", "Y", "Z"}


class TestLieClosureMatrices:
    @pytest.mark.unittest
    def test_su2_closure_dimension(self):
        assert len(lie_closure_matrices([_X, _Y])) == 3

    @pytest.mark.unittest
    def test_orthonormal_hermitian(self):
        basis = lie_closure_matrices([_X, _Y])
        for B in basis:
            assert np.allclose(B, B.conj().T)
        gram = np.array(
            [[np.vdot(a.reshape(-1), b.reshape(-1)) for b in basis] for a in basis]
        )
        assert np.allclose(gram, np.eye(len(basis)))

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_matchgate_dimension_matches_paulis(self, n):
        gens = _matchgate_generators(n)
        mats = [
            np.asarray(PauliWord.from_pauli_string(s, list(range(n)), n).to_matrix())
            for s in gens
        ]
        basis = lie_closure_matrices(mats)
        assert len(basis) == n * (2 * n - 1)
        assert len(basis) == len(lie_closure_paulis(gens))


class TestMatchgateConstructors:
    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_dim_so2n(self, n):
        assert dim_so2n(n) == n * (2 * n - 1)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_basis_length(self, n):
        assert len(matchgate_basis(n)) == dim_so2n(n)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_generators_count(self, n):
        assert len(matchgate_generators(n)) == n + (n - 1)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_generators_match_reference(self, n):
        assert matchgate_generators(n) == _matchgate_generators(n)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_basis_equals_closure(self, n):
        # Explicit construction must equal the frontier-expansion closure.
        closure = {
            pw.to_pauli_string() for pw in lie_closure_paulis(matchgate_generators(n))
        }
        assert set(matchgate_basis(n)) == closure


class TestGPurity:
    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_from_basis_all_zero_value(self, n):
        # |0...0>: <Z_k> = 1 for the n on-site terms, all X/Y pair strings -> 0.
        psi = np.zeros(2**n, dtype=complex)
        psi[0] = 1.0
        assert np.isclose(
            g_purity_from_basis(psi, matchgate_basis(n)), float(n), atol=1e-10
        )

    @pytest.mark.unittest
    def test_from_basis_accepts_words_and_strings(self):
        n = 2
        psi = _product_state(np.array([0.7, 1.3]))
        words = lie_closure_paulis(matchgate_generators(n))
        strs = [pw.to_pauli_string() for pw in words]
        assert np.isclose(
            g_purity_from_basis(psi, words),
            g_purity_from_basis(psi, strs),
            atol=1e-12,
        )

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_matrix_matches_from_basis(self, n):
        # P_g^HS = P_g / 2^n on the same DLA (HS-orthonormal P_mu / sqrt(2^n)).
        theta = np.linspace(0.3, 1.1, n)
        psi = _product_state(theta)
        strings = matchgate_basis(n)
        p_str = g_purity_from_basis(psi, strings)
        p_mat = g_purity_matrix(psi, _normalised_pauli_mats(strings, n))
        assert np.isclose(p_mat, p_str / 2**n, atol=1e-10)

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_matrix_basis_independent(self, n):
        # g_purity_matrix is invariant to the HS-orthonormal basis choice:
        # lie_closure_matrices output equals the manually normalised Pauli basis.
        theta = np.linspace(0.2, 1.4, n)
        psi = _product_state(theta)
        manual = _normalised_pauli_mats(matchgate_basis(n), n)
        closed = lie_closure_matrices(
            [
                np.asarray(
                    PauliWord.from_pauli_string(s, list(range(n)), n).to_matrix()
                )
                for s in matchgate_generators(n)
            ]
        )
        assert np.isclose(
            g_purity_matrix(psi, manual), g_purity_matrix(psi, closed), atol=1e-10
        )
