"""Tests for the dynamical Lie algebra closure helpers.

Closure dimensions are validated against closed-form values: the single-qubit
algebra su(2) has dimension 3, and the matchgate algebra so(2n) generated by
{Z_k} u {X_k X_{k+1}} has dimension n(2n-1).
"""

import numpy as np
import pytest

from qml_essentials.algebra import lie_closure_paulis, lie_closure_matrices
from qml_essentials.operations import PauliWord

_X = np.array([[0, 1], [1, 0]], dtype=complex)
_Y = np.array([[0, -1j], [1j, 0]], dtype=complex)


def _matchgate_generators(n):
    """Matchgate DLA generators {Z_k} u {X_k X_{k+1}}."""
    gens = []
    for k in range(n):
        s = ["I"] * n
        s[k] = "Z"
        gens.append("".join(s))
    for k in range(n - 1):
        s = ["I"] * n
        s[k] = "X"
        s[k + 1] = "X"
        gens.append("".join(s))
    return gens


class TestLieClosurePaulis:
    @pytest.mark.unittest
    def test_su2_closure(self):
        basis = lie_closure_paulis(["X", "Y"])
        assert {pw.to_pauli_string() for pw in basis} == {"X", "Y", "Z"}

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3, 4])
    def test_matchgate_dimension(self, n):
        basis = lie_closure_paulis(_matchgate_generators(n))
        assert len(basis) == n * (2 * n - 1)

    @pytest.mark.unittest
    def test_accepts_pauliword_inputs(self):
        gens = [PauliWord.from_pauli_string(s, [0], 1) for s in ("X", "Y")]
        basis = lie_closure_paulis(gens)
        assert {pw.to_pauli_string() for pw in basis} == {"X", "Y", "Z"}


class TestLieClosureMatrices:
    @pytest.mark.unittest
    def test_su2_closure_dimension(self):
        assert len(lie_closure_matrices([_X, _Y])) == 3

    @pytest.mark.unittest
    def test_orthonormal_hermitian(self):
        basis = lie_closure_matrices([_X, _Y])
        for B in basis:
            assert np.allclose(B, B.conj().T)
        gram = np.array(
            [[np.vdot(a.reshape(-1), b.reshape(-1)) for b in basis] for a in basis]
        )
        assert np.allclose(gram, np.eye(len(basis)))

    @pytest.mark.unittest
    @pytest.mark.parametrize("n", [2, 3])
    def test_matchgate_dimension_matches_paulis(self, n):
        gens = _matchgate_generators(n)
        mats = [
            np.asarray(PauliWord.from_pauli_string(s, list(range(n)), n).to_matrix())
            for s in gens
        ]
        basis = lie_closure_matrices(mats)
        assert len(basis) == n * (2 * n - 1)
        assert len(basis) == len(lie_closure_paulis(gens))
