r"""Dynamical Lie algebra (DLA) closure helpers.

The DLA :math:`\mathfrak{g} = \langle i G \rangle_{\mathrm{Lie}}` of a set of
Hermitian generators :math:`G` is the real Lie algebra spanned by repeated
brackets.  Two representations are provided:

- :func:`lie_closure_paulis` for generators given as Pauli words or strings.
  Every bracket :math:`[i P_a, i P_b]` is again proportional to a single Pauli
  string, so the closure is the set of Pauli strings reached by composing
  anticommuting pairs.
- :func:`lie_closure_matrices` for generators given as dense Hermitian matrices
  (for example sums of Paulis), returning a Hilbert-Schmidt-orthonormal
  Hermitian basis.

In both cases the length of the returned basis equals
:math:`\dim \mathfrak{g}`.

The matchgate algebra :math:`\mathfrak{so}(2n)` is also provided explicitly by
:func:`matchgate_generators`, :func:`matchgate_basis`, and :func:`dim_so2n`.
The g-purity of a state with respect to a DLA basis is given by
:func:`g_purity_from_basis` (Pauli-word basis) and :func:`g_purity_matrix`
(Hilbert-Schmidt-orthonormal matrix basis).

Permutation-symmetric operators are built by :func:`symmetric_pauli_sum`, with
:func:`sn_equivariant_generators` and :func:`sn_equivariant_observable` giving the
generators and observable of the :math:`S_n`-equivariant ansatz; the generators
feed the matrix DLA via :func:`lie_closure_matrices`.
"""

from itertools import combinations
from typing import List, Union

import numpy as np

from qml_essentials.operations import PauliWord, state_expectation


def lie_closure_paulis(
    generators: List[Union[str, PauliWord]],
) -> List[PauliWord]:
    r"""Return the Pauli-word spanning set of the DLA generated by *generators*.

    Each generator is a Hermitian Pauli word :math:`P` (standing for
    :math:`i P` in :math:`\mathfrak{g}`).  The closure is grown by repeatedly
    composing anticommuting pairs; every such product is again a single Pauli
    word.  Deduplication is on the bare Pauli string (the global phase does not
    affect the span), and the returned words carry that bare string.  The
    length of the result is :math:`\dim \mathfrak{g}`.

    Args:
        generators: Hermitian generators, each a :class:`PauliWord` or a bare
            Pauli string over ``{'I', 'X', 'Y', 'Z'}`` (qubit 0 leftmost).

    Returns:
        The list of Pauli words spanning :math:`i \mathfrak{g}`.
    """

    def _word(s: str) -> PauliWord:
        return PauliWord.from_pauli_string(s, list(range(len(s))), len(s))

    seen: set = set()
    basis: List[PauliWord] = []

    def _add(s: str) -> bool:
        if s in seen:
            return False
        seen.add(s)
        basis.append(_word(s))
        return True

    for g in generators:
        _add(g if isinstance(g, str) else g.to_pauli_string())

    frontier = list(basis)
    while frontier:
        new: List[PauliWord] = []
        pool = list(basis)
        for a in frontier:
            for b in pool:
                if a.commutes_with(b):
                    continue
                if _add(a.compose(b).to_pauli_string()):
                    new.append(basis[-1])
        frontier = new
    return basis


def lie_closure_matrices(gens: List[np.ndarray], tol: float = 1e-9) -> List[np.ndarray]:
    r"""Return an HS-orthonormal Hermitian basis of the real Lie algebra.

    The algebra is generated by the Hermitian matrices *gens* under the bracket
    :math:`i [A, B]` (which preserves Hermiticity).  Each candidate is
    orthonormalised against the current basis in the Hilbert-Schmidt inner
    product; candidates with norm below *tol* are discarded as dependent.  The
    length of the result is :math:`\dim \mathfrak{g}`.

    Args:
        gens: Hermitian generator matrices.
        tol: Linear-independence threshold on the Hilbert-Schmidt norm.

    Returns:
        The HS-orthonormal Hermitian basis matrices of :math:`i \mathfrak{g}`.
    """
    basis_vecs: List[np.ndarray] = []
    basis_mats: List[np.ndarray] = []

    def add(M: np.ndarray):
        M = np.asarray(M, dtype=complex)
        v = M.reshape(-1)
        for b in basis_vecs:
            v = v - np.vdot(b, v) * b
        nrm = np.linalg.norm(v)
        if nrm < tol:
            return None
        v = v / nrm
        basis_vecs.append(v)
        basis_mats.append(v.reshape(M.shape))
        return basis_mats[-1]

    frontier = [m for g in gens if (m := add(g)) is not None]
    while frontier:
        current = list(basis_mats)
        new = []
        for A in frontier:
            for B in current:
                m = add(1j * (A @ B - B @ A))
                if m is not None:
                    new.append(m)
        frontier = new
    return basis_mats


def matchgate_generators(n: int) -> List[str]:
    r"""Return the matchgate DLA generators :math:`\{Z_k\} \cup \{X_k X_{k+1}\}`.

    These Hermitian Pauli strings generate the matchgate algebra
    :math:`\mathfrak{so}(2n)` under :func:`lie_closure_paulis`.

    Args:
        n: Number of qubits.

    Returns:
        The generator Pauli strings (qubit 0 leftmost).
    """
    gens: List[str] = []
    for k in range(n):
        s = ["I"] * n
        s[k] = "Z"
        gens.append("".join(s))
    for k in range(n - 1):
        s = ["I"] * n
        s[k] = "X"
        s[k + 1] = "X"
        gens.append("".join(s))
    return gens


def matchgate_basis(n: int) -> List[str]:
    r"""Return the explicit Pauli-string basis of :math:`\mathfrak{so}(2n)`.

    The basis is the :math:`n` on-site :math:`Z_k`, and for each pair
    :math:`j < k` the four strings
    :math:`\sigma_j \left( \prod_{j < l < k} Z_l \right) \sigma'_k` with
    :math:`\sigma, \sigma' \in \{X, Y\}`.  Its length is
    :math:`n + 4\binom{n}{2} = n(2n-1) = \dim \mathfrak{so}(2n)`.

    Args:
        n: Number of qubits.

    Returns:
        The basis Pauli strings (qubit 0 leftmost).
    """
    basis: List[str] = []
    for k in range(n):
        s = ["I"] * n
        s[k] = "Z"
        basis.append("".join(s))
    for j, k in combinations(range(n), 2):
        for sj in ("X", "Y"):
            for sk in ("X", "Y"):
                s = ["I"] * n
                s[j] = sj
                s[k] = sk
                for ell in range(j + 1, k):
                    s[ell] = "Z"
                basis.append("".join(s))
    return basis


def dim_so2n(n: int) -> int:
    r"""Return :math:`\dim \mathfrak{so}(2n) = n(2n-1)`."""
    return n * (2 * n - 1)


def g_purity_from_basis(
    state: np.ndarray,
    basis: List[Union[str, PauliWord]],
) -> float:
    r"""Return the g-purity :math:`P_g = \sum_B \langle\psi|B|\psi\rangle^2`.

    Each basis element :math:`B` is a Hermitian Pauli word, so its expectation
    is real and :math:`P_g` is the squared 2-norm of the expectation vector in
    the DLA basis.  The basis is typically :func:`matchgate_basis` or the output
    of :func:`lie_closure_paulis`.

    Args:
        state: Statevector of shape ``(2**n,)`` (qubit 0 leftmost).
        basis: Hermitian Pauli words, each a :class:`PauliWord` or a bare Pauli
            string over ``{'I', 'X', 'Y', 'Z'}``.

    Returns:
        The g-purity :math:`P_g`.
    """
    return float(sum(state_expectation(B, state).real ** 2 for B in basis))


def g_purity_matrix(
    state: np.ndarray,
    basis_mats: List[np.ndarray],
) -> float:
    r"""Return the g-purity against an HS-orthonormal Hermitian matrix basis.

    Computes :math:`P_g^{\mathrm{HS}} = \sum_\mu |\langle\psi|B_\mu|\psi\rangle|^2`
    for a Hilbert-Schmidt-orthonormal Hermitian basis :math:`\{B_\mu\}` of
    :math:`i\mathfrak{g}`, for example the output of :func:`lie_closure_matrices`.

    Args:
        state: Statevector of shape ``(2**n,)``.
        basis_mats: HS-orthonormal Hermitian basis matrices.

    Returns:
        The g-purity :math:`P_g^{\mathrm{HS}}`.
    """
    psi = np.asarray(state, dtype=complex)
    return float(sum(abs(np.vdot(psi, B @ psi)) ** 2 for B in basis_mats))


def symmetric_pauli_sum(pauli: str, n: int, locality: int = 1) -> np.ndarray:
    r"""Return the symmetric sum of a Pauli over all ``locality``-qubit subsets.

    The permutation-symmetric operator
    :math:`\sum_{S} \prod_{q \in S} P_q` where :math:`P` is the single-qubit
    Pauli *pauli* and :math:`S` ranges over all size-``locality`` subsets of the
    :math:`n` qubits.  For example ``locality=1`` gives :math:`\sum_k P_k` and
    ``locality=2`` gives :math:`\sum_{j<k} P_j P_k`.  The result is Hermitian.

    Args:
        pauli: Single-qubit Pauli, one of ``{'I', 'X', 'Y', 'Z'}``.
        n: Number of qubits.
        locality: Subset size, with :math:`1 \leq \text{locality} \leq n`.

    Returns:
        The dense Hermitian operator of shape :math:`(2^n, 2^n)`.

    Raises:
        ValueError: If ``pauli`` is not a Pauli label or ``locality`` is outside
            ``[1, n]``.
    """
    if pauli not in {"I", "X", "Y", "Z"}:
        raise ValueError(f"pauli must be one of I, X, Y, Z, got {pauli!r}")
    if not 1 <= locality <= n:
        raise ValueError(
            f"locality must satisfy 1 <= locality <= n, "
            f"got locality={locality} for n={n}"
        )
    dim = 2**n
    acc = np.zeros((dim, dim), dtype=complex)
    for subset in combinations(range(n), locality):
        s = ["I"] * n
        for q in subset:
            s[q] = pauli
        acc += np.asarray(
            PauliWord.from_pauli_string("".join(s), list(range(n)), n).to_matrix()
        )
    return acc


def sn_equivariant_generators(n: int) -> List[np.ndarray]:
    r"""Return the :math:`S_n`-equivariant generators
    :math:`\{\sum_k X_k, \sum_k Y_k, \sum_{j<k} Z_j Z_k\}`.

    The three Hermitian generators of the permutation-equivariant ansatz of
    Schatzki et al. (arXiv:2210.09974).  They are unnormalised (the scaling is
    irrelevant for the Lie closure) and feed :func:`lie_closure_matrices`.

    Args:
        n: Number of qubits, with :math:`n \geq 2` (the pair term needs two).

    Returns:
        The list of three generator matrices, each of shape :math:`(2^n, 2^n)`.

    Raises:
        ValueError: If ``n < 2``.
    """
    if n < 2:
        raise ValueError(f"n must be at least 2, got {n}")
    return [
        symmetric_pauli_sum("X", n, 1),
        symmetric_pauli_sum("Y", n, 1),
        symmetric_pauli_sum("Z", n, 2),
    ]


def sn_equivariant_observable(n: int) -> np.ndarray:
    r"""Return the :math:`S_n`-equivariant observable
    :math:`O = \frac{2}{n(n-1)} \sum_{j<k} X_j X_k`.

    The permutation-symmetric observable of Schatzki et al. (arXiv:2210.09974),
    normalised by the number of pairs.

    Args:
        n: Number of qubits, with :math:`n \geq 2`.

    Returns:
        The dense Hermitian observable of shape :math:`(2^n, 2^n)`.

    Raises:
        ValueError: If ``n < 2``.
    """
    if n < 2:
        raise ValueError(f"n must be at least 2, got {n}")
    return (2.0 / (n * (n - 1))) * symmetric_pauli_sum("X", n, 2)
