name: Quality
on:
  pull_request:
    branches: ["main"]
permissions:
  contents: read
env:
  UV_PYTHON: "3.13"
jobs:
  quality:
    runs-on: self-hosted
    if: ${{ (github.actor != 'dependabot[bot]') }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync --group dev
      - name: Lint with ruff
        run: |
          uv run ruff check qml_essentials
          uv run ruff check tests
      - name: Running license check
        run: uv run licensecheck --zero --license mit
