name: Testing on PR
on:
  pull_request:
    branches: ["main"]
  workflow_call:
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  UV_PYTHON: "3.13"
jobs:
  test-all:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync --group dev
      - name: Test with pytest (no benchmark)
        run: uv run pytest --cov=qml_essentials --dist load -n 2 -m "not benchmark" -v
      - name: Test with pytest (benchmark)
        run: uv run pytest --cov=qml_essentials -m "benchmark"
