name: Testing on Publish
on:
  workflow_call:
permissions:
  contents: write
env:
  UV_PYTHON: "3.13"
jobs:
  test-all:
    runs-on: self-hosted
    if: ${{ (github.actor != 'github-actions[bot]') }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync --group dev
      - name: Test with pytest (no benchmark)
        run: uv run pytest --cov=qml_essentials --cov-report html --dist load -n 0 -m "not benchmark"
      - name: Share coverage report
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: htmlcov/
